
# Source: [OpenAI Documentation](https://platform.openai.com/docs/guides/function-calling)

from openai import OpenAI
from dotenv import load_dotenv
import json
import requests

load_dotenv(r"D:\DSI\deploying-ai\05_src\.secrets")

client = OpenAI()

tools = [
    {
        "type": "function",
        "name": "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Taurus or Aquarius",
                },
                "day": {
                    "type": "string",
                    "description": 'The day to get the horoscope for. Can be "TODAY", "TOMORROW", "YESTERDAY" or a date in format (YYYY-MM-DD). Defaults to "TODAY".',
                    "default": "TODAY",
                }
            },
            "required": ["sign"],
        },
    },
]

# The function that makes the API call
# 
def get_horoscope(sign, day="TODAY"):
    """
    An API call to a horoscope service is made.
    The API call is to https://horoscope-app-api.vercel.app/api/v1/get-horoscope/daily
    and takes two parameters sign and day.
    Accepted values for sign are: Aries, Taurus, Gemini, Cancer, Leo, Virgo, Libra, Scorpio, Sagittarius, Capricorn, Aquarius, Pisces
    Accepted values for day are: Date in format (YYYY-MM-DD) OR "TODAY" OR "TOMORROW" OR "YESTERDAY".
    """
    
    response = get_horoscope_from_service(sign, day)
    horoscope = get_horoscope_from_response(sign, response)
    return horoscope

# Helper functions for the API call
# We need this because we want to separate the API call from the response parsing. 
def get_horoscope_from_service(sign, day):
    url = "https://horoscope-app-api.vercel.app/api/v1/get-horoscope/daily"
    params = {
        "sign": sign.capitalize(),
        "day": day.upper()
    }
    response = requests.get(url, params=params)
    return response

# Helper function to parse the API response
# in plain english it means: extract the horoscope from the response json to use it in our main function

def get_horoscope_from_response(sign, response):
    resp_dict = json.loads(response.text)
    data = resp_dict.get("data")
    horoscope_data = data.get("horoscope_data", "No horoscope found.")
    date = data.get("date", "No date found.")
    horoscope = f"Horoscope for {sign.capitalize()} on {date}: {horoscope_data}"
    return horoscope

# Main logic

input_list = [
    {"role": "user", "content": "What is the horoscope for Capricorn?"}
]
# Initial response to get the function call
response = client.responses.create(
    model="gpt-5", 
    tools = tools,
    input=input_list
)
# Append the response to the input list for further processing
# it means we are adding the model's response to our conversation history so we can continue the interaction
# in terms of memory, we are keeping track of the conversation context contracy to the otherwise stateless approach

input_list += response.output

# Process the function call if there is one
# it means we are checking if the model requested to call a function and if so, we execute that function

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            args = json.loads(item.arguments)
            horoscope = get_horoscope(**args)

            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                    "horoscope": horoscope
                })
            })

print("Final input:")
print(input_list)
# Final response to get the horoscope from the function call
# it means we are addng the function call output to the conversation and asking the model to generate a final response based on that
# in terms of memory, we are ensuring the model has all the necessary information to provide a coherent and contextually relevant answer
# if we used parse instead of create, we would be parsing an existing response rather than generating a new one 
# this is important because we want the model to produce a new output based on the updated conversation context

response = client.responses.create(
    model="gpt-5", 
    instructions="Respond only with a horoscope generated by a tool.",
    tools = tools,
    input=input_list
)

print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)